macro(DEB msg)
    if( BAGCNV_DEBUG_CMAKE )
        message(        STATUS " * ${msg}" )
    endif()
endmacro()

macro(DEB_START msg)
    if( BAGCNV_DEBUG_CMAKE )
        message(        STATUS "--> ${msg} start" )
    endif()
endmacro()

macro(DEB_END msg)
    if( BAGCNV_DEBUG_CMAKE )
        message(        STATUS "<-- ${msg} end" )
    endif()
endmacro()

macro(DEBUG ln msg)
    if( BAGCNV_DEBUG_CMAKE )
        message(        STATUS "[${CMAKE_CURRENT_LIST_FILE}:${ln}] > ${msg}" )
    endif()
endmacro()

macro(DEBUG_VALUE variableName)
    DEBUG(              "${variableName}=\${${variableName}}")
endmacro()

macro(DEBUG_INCLUDE_DIRS ln msg)
    if( BAGCNV_DEBUG_CMAKE )
        message(        STATUS "[${CMAKE_CURRENT_LIST_FILE}:${ln}] > include dirs for ${msg}:" )
        get_property(   inc_dirs DIRECTORY  PROPERTY INCLUDE_DIRECTORIES )
        foreach( dir ${inc_dirs} )
            message(    STATUS "   - ${dir} " )
        endforeach()
    endif()
endmacro()

macro(DEB_INCLUDE_DIRS)
    if( BAGCNV_DEBUG_CMAKE )
        message(        STATUS "> include dirs:" )
        get_property(   inc_dirs DIRECTORY  PROPERTY INCLUDE_DIRECTORIES )
        foreach( dir ${inc_dirs} )
            message(    STATUS "  |- ${dir} " )
        endforeach()
    endif()
endmacro()
