DEB_START("Version")

set( BAG_CONVERTER_VERS_FILE  "${CMAKE_SOURCE_DIR}/src/version.h" )
file( STRINGS "${BAG_CONVERTER_VERS_FILE}" BAG_CONVERTER_VERS_PARTS REGEX "#define BAG_CONVERTER_VERS_[A-Z]+[ ]+" ) # Store lines with token
#DEB( ${BAG_CONVERTER_VERS_PARTS} )
string( REGEX REPLACE  ".+BAG_CONVERTER_VERS_MAJ[ ]+([0-9]+).*" "\\1"  BAG_CONVERTER_VERS_MAJ "${BAG_CONVERTER_VERS_PARTS}" ) # Major version
string( REGEX REPLACE  ".+BAG_CONVERTER_VERS_MIN[ ]+([0-9]+).*" "\\1"  BAG_CONVERTER_VERS_MIN "${BAG_CONVERTER_VERS_PARTS}" ) # Minor version
string( REGEX REPLACE  ".+BAG_CONVERTER_VERS_FIX[ ]+([0-9]+).*" "\\1"  BAG_CONVERTER_VERS_FIX "${BAG_CONVERTER_VERS_PARTS}" ) # Fix version
set( BAGCNV_VERSION  "${BAG_CONVERTER_VERS_MAJ}.${BAG_CONVERTER_VERS_MIN}.${BAG_CONVERTER_VERS_FIX}"  CACHE STRING "BAG Converter version"  FORCE )
DEB( "BAG Converter version: ${BAG_CONVERTER_VERS_MAJ}.${BAG_CONVERTER_VERS_MIN}.${BAG_CONVERTER_VERS_FIX}" )

DEB_END("Version")
